### ISSUE TITLE
Hi, is it still working?

### ISSUE THREAD

**Issue by oguzhanbahadir** [nirajx1d/video_stream_WebRTC#1]
Hello there, im trying to make it work but it seems its not working. Im starting stream but i cant see my camera and i cant connect from another page. It says User is not streaming!, can you help me some?

**Comment by perun-01** [comment]
hey  [oguzhanbahadir](https://github.com/oguzhanbahadir) , u have to create a pubnub account for that and enter the two keys given in ur account to run it. And also check ur browser support for webrtc as webrtc is not supported by all web browsers. Also if u re using Firefox browser, then in (about:config) change (media.peerconnection.ice.proxy_only) to true if it is false.
